tweaks

diff --git a/resources/rsync-wrapper b/resources/rsync-wrapper
--- a/resources/rsync-wrapper
+++ b/resources/rsync-wrapper
@@ -20,7 +20,179 @@ set -eE
 # Trap signals
 
 trap 'exit_non_zero $LINENO' ERR
+trap 'exit_zero' EXIT SIGINT#!/bin/bash
+
+# Exit on error, functions inherit parent scope for traps (-E same as `set -o errexit -o errtrace`)
+
+set -eE
+
+# Standard signal / pseudo-signal cheat sheet:
+
+#   DEBUG:      This signal triggers right before a command is to be run.
+#   ERR:        When a command ends in a non-zero status triggers this trap. Be aware that commands in if statements, loops, or strung-together commands may not trigger this signal.
+#   EXIT:       The EXIT trap is used to specify actions that should be done before the script exits (zero as well as non-zero).
+#   RETURN:     The RETURN signal is triggered after a function or sourced script exits.
+#   SIGINT:     Interrupt from keyboard (ctrl + c)
+#   SIGTERM:    Termination signal
+
+# NOTE: You need single quotes to prevent $LINENO from being expanded when the trap line is first parsed.
+
+# NOTE: Thanks to -E / -o errtrace, this still triggers the trap, even if a failure occurs *inside a function / loop*. With -e (but without -E), when a command fails inside a function, bash *instantly* exits, directly from the function scope - and since there is no ERR trap in effect there (because it wasn't inherited from the parent scope), your trap is not called. Source: https://stackoverflow.com/questions/35800082/how-to-trap-err-when-using-set-e-in-bash
+
+# Trap signals
+
+trap 'exit_non_zero $LINENO' ERR
 trap 'exit_zero' EXIT SIGINT
+
+# Declare constants
+
+LOCKFILE="/tmp/rsync-wrapper.lock"
+LOG_FOLDER="/home/jonathan/Desktop"
+REMOTE="jonathan@raspberry-pi"
+
+LOG="${LOG_FOLDER}/rsync-wrapper.log"
+LOG_ERROR="${LOG_FOLDER}/ERROR.log"
+
+##############################################
+#                                            #
+#          BEGIN USER CONFIGURATION          #
+#                                            #
+##############################################
+
+declare -a job=(
+    
+    APPLICATIONS
+    FILES
+    MUSIC
+    SHARED_FILES
+    SSH
+    WINDOWS_FILES
+    
+    )
+
+declare -A source=(
+
+    [APPLICATIONS]="/home/jonathan/Applications"
+    [FILES]="/mnt/d/Files"
+    [MUSIC]="/mnt/d/Music"
+    [SHARED_FILES]="/mnt/c/Users/Jonathan/Desktop/Shared Files"
+    [SSH]="/home/jonathan/Desktop/@ssh"
+    [WINDOWS_FILES]="/mnt/c/Users/Jonathan/Desktop"
+
+)
+
+declare -A destination=(
+
+    [APPLICATIONS]="${REMOTE}:/filepacks/@applications"
+    [FILES]="${REMOTE}:/filepacks/@files"
+    [MUSIC]="${REMOTE}:/filepacks/@music"
+    [SHARED_FILES]="${REMOTE}:/filepacks/@shared-files"
+    [SSH]="${REMOTE}:/filepacks/@ssh"
+    [WINDOWS_FILES]="${REMOTE}:/filepacks/@windows-files"
+
+)
+
+############################################
+#                                          #
+#          END USER CONFIGURATION          #
+#                                          #
+############################################
+
+run_rsync() {
+
+    rsync \
+            --append \
+            --archive \
+            --exclude *".lnk" \
+            --exclude "desktop.ini" \
+            --exclude "Google Drive" \
+            --exclude "iCloud Drive" \
+            --exclude "Images" \
+            --exclude '$RECYCLE.BIN' \
+            --exclude ".snapshots" \
+            --exclude "System Volume Information" \
+            --exclude ".Trash"* \
+            --info=progress2 \
+            --partial \
+            "$1" \
+            "$2"
+
+}
+
+write_log_error() {
+
+    [ ! -f "$LOG_ERROR" ] && touch "$LOG_ERROR"
+
+    echo "$1" >> "$LOG_ERROR"
+
+}
+
+write_log() {
+
+    [ ! -f "$LOG" ] && touch "$LOG"
+
+    echo "$1" >> "$LOG"
+
+}
+
+exit_non_zero() {
+
+    message="Error on line $1"
+
+    echo "$message"
+    
+    write_log_error "$message"
+
+    [ -d "$LOCKFILE" ] && rmdir "$LOCKFILE"
+
+}
+
+exit_zero() {
+
+    # Release the lock "file"
+
+    [ -d "$LOCKFILE" ] && rmdir "$LOCKFILE"
+
+    echo
+    echo "  Completed successfully!"
+    echo
+
+}
+
+main() {
+
+    # Try to acquire the lock
+
+    if mkdir "$LOCKFILE"; then
+
+        # Lock acquired, perform rsync backups
+
+        for i in "${job[@]}"; do
+
+            # (NOTE: The reason you're not backing up windows files with robocopy is because you want checksums.)
+
+            echo
+            echo "Source:      ${source[$i]}"
+            echo "Destination: ${destination[$i]}"
+
+            run_rsync "${source[$i]}/" "${destination[$i]}/"
+
+        done
+
+    else
+
+        # Unable to acquire the lock, a previous instance is still running
+
+        message="Previous rsync job is still in progress (LOCKFILE path: ${LOCKFILE}), exiting..."
+
+        echo "$message"
+
+    fi
+
+}
+
+main
+
 
 # Declare constants
 
